# create pipelines with some name
name: mli10 app containerization pipelines
# Trigger -- when this pipleline should start
on:
  push:
    branches:
      - "dev"

# jobs for performing operations
jobs:
  mli10-sast-job:  
    runs-on: self-hosted
    steps:
      - name: checking docker version and sonarqube-scanner
        run: |
          date
          # sonar-scanner --version
      - name: fetch git code
        uses: actions/checkout@v4

      # - name: SonarQube Scan
      #   uses: SonarSource/sonarqube-scan-action@v2.1.0
      #   with:
      #     projectBaseDir: .
      #     args: >
      #       -Dsonar.projectKey=mli10-python-project
      #   env:
      #     SONAR_TOKEN: sqp_7ec9083e23d578cfcd2ae54e5db8b101efdd66eb
      #     SONAR_HOST_URL: http://44.219.46.64:9000/
      - name: using local sonar runner
        run: |
          pwd
           C:\Users\user\Downloads\sonar-scanner\sonar-scanner-5.0.1.3006-windows\bin\sonar-scanner.bat -D"sonar.projectKey=mli10-python-project" -D"sonar.sources=." -D"sonar.host.url=${{ secrets.SONAR_HOST_URL }}" -D"sonar.token=${{ secrets.SONAR_TOKEN }}"


  mli10-build-job:
    runs-on: macos-latest
    needs: mli10-sast-job
    steps:
      - name: just check general messages
        run: |
          echo "python version checking"
          python -V