# create pipelines with some name
name: mli10 app containerization pipelines
# Trigger -- when this pipleline should start
on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]   
    # branches:
    #   - "main"

# jobs for performing operations
jobs:
  mli10-image-build:
    runs-on: ubuntu-latest
    # this server will be provision by github backen for this job
    steps:
      - name: run some basic commands on above server to verify
        run: |
          uname -r
          whoami
          cat /etc/os-release
          docker version
          docker-compose version
      - name: using pre-design github workflow to get copy gitrepo code to runners machine
        uses: actions/checkout@v4

      - name: verify github code
        run: |
          ls -a
          docker-compose up -d
          sleep 2
          docker-compose ps 

      - name: verify health check page by access it usign postman / curl 
        run: |
          echo  "access health.html page using curl "
          curl -f  http://localhost:1234/health.html
          # here we will get http response code 200 

      - name: try to login from runner to docker hub account 
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.MLI10_USER }}
          password: ${{ secrets.MLI10_PASSWORD }}

      - name: rebuild image in docker hub format and push it to docker hub
        run: |
          echo "this is home work for guys "
          echo "plz find some action workflow "
          echo "build image in docker hub format and push also " 
        